### ISSUE TITLE
Blank pages on Gizmodo 

### ISSUE THREAD

**Issue by valuesindesign** [dhowe/AdNauseam#1509]
From email:
> I recently downloaded and installed AdNauseam for Chrome. The extension is functioning properly with most websites I normally visit. I am currently having issues with one group of sites; the Gizmodo family of pages. If I visit any of the Gizmodo blogs (Gizmodo, Jalopnik, Kotaku, etc), AdNauseam will detect ads, click them, but I will only be provided a white page with no content. I disabled AdNauseam, refreshed the page, and everything loaded like normal. I have not had this problem when using other developers ad blocking extensions. I was wondering if you were aware of this issue and if there was some sort of work around to use your extension, but still have access to the Gizmodo content? Thank you for any assistance you can provide.

**Comment by cqx931** [comment]
Hi @valuesindesign I just checked this issue [here](https://github.com/dhowe/uAssets/commit/0d755c9acf6805cb2c06454433e1f557e7a86800) and it was a problem caused by one of the adnauseam specific filters. Please update your Adnauseam filter and the issue should be fixed.

**Comment by cqx931** [comment]
closed for now

**Comment by joshsleeper** [comment]
@cqx931 I'm still seeing the issue exactly as was described on all Gizmodo sites _except_ www.gizmodo.com, so I don't think it's fixed properly in adnauseam just yet. For the record, running uBlock Origin's latest release directly I have no such issue on these pages.

also, is it just me, or is that fork of uAssets _very_ behind the official one upstream?
![image](https://user-images.githubusercontent.com/849941/60216431-06bab280-9838-11e9-9a00-6de39941a166.png)

**Comment by cqx931** [comment]
@joshsleeper. Thank you, yes you are right.I thought the problem was just on gizmodo.

I figured out the starting point of the teads filters, and they should be added for scmp.com. Not sure when the domain names are removed.
https://github.com/dhowe/AdNauseam/issues/1313
As I have added back the specific domain name, this issue should be fixed for all gizmodo blogs.

**Comment by dhowe** [comment]
Can this be closed?

**Comment by joshsleeper** [comment]
sorry, had been waiting for a while for the update to show up for Firefox and forgot to respond.

as of the latest update, I am _still_ seeing Gizmodo pages such as kotaku.com and jalopnik.com loading improperly, so I would request leaving this issue open for now.

if you want to see what I'm talking about, I _think_ it should be as simple as installing the latest extension in the latest Firefox and navigating to https://www.kotaku.com with the extension enabled.

the page loads properly briefly, then immediately goes blank and never returns.

**Comment by dhowe** [comment]
Confirmed on Firefox 68.0.1 (64-bit)

![image](https://user-images.githubusercontent.com/737638/62912068-923ec300-bd54-11e9-8092-9689f3533ad0.png)

@cqx931 can you take a look at this?

**Comment by mneunomne** [comment]
This doenst seem to be happening any longer with Firefox 89.0 (64-bit). Tested on websites https://jalopnik.com/ and https://kotaku.com/

**Comment by mneunomne** [comment]
But there seemed to be a blank ad container appearing, fixed with this PR  https://github.com/dhowe/AdNauseam/pull/1876. Closing for now.
