### ISSUE TITLE
Ads visible on Youtube

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#2385]
As reported via several email users...

**Comment by RowanSkie** [comment]
I believe it was earlier this week, not just today. I pushed my AdNauseam to the beta branch just earlier thinking it was just outdated.

When I run a YouTube video, I get the pre-video ad that automatically vanishes after a quick refresh.

**Comment by undeadcorvid** [comment]
I came here to report the same issue - I can't see the ad, all I see is a black screen, but I can hear it, and all the usual YouTube ad UX pops up.

**Comment by JCD3nt0n** [comment]
Confirming that firefox 111.0.1 adnauseum 3.17.0
Black screen audio only, only the time skip buttons pop up for the first ad video and hitting skip button when unlocked terminates any all the remaining adds without playing the next.
Changed profiles, reinstalled firefox, ditto for adnauseum and even double down on the blocklists.

**Comment by BaconCatBug** [comment]
> Confirming that firefox 111.0.1 adnauseum 3.17.0 Black screen audio only, only the time skip buttons pop up for the first ad video and hitting skip button when unlocked terminates any all the remaining adds without playing the next. Changed profiles, reinstalled firefox, ditto for adnauseum and even double down on the blocklists.

Same issue here, no ad plays, but the ad wrapper does.

**Comment by dhowe** [comment]
can someone confirm whether this is also happening with ublock origin?

**Comment by BaconCatBug** [comment]
> can someone confirm whether this is also happening with ublock origin?

It has not happened to me since I switched to uBlock Origin, but the whole you can't prove a negative thing, I'll post back if it does happen.

**Comment by JCD3nt0n** [comment]
> can someone confirm whether this is also happening with ublock origin?

Further testing is required but apparently installed origin disabled adnauseum run a couple videos and nothing, disabled origin ran a couple of videos and got ads to play, re-enabled adnauseum and the behaviour stopped weird. Further testing required.

**Comment by Ozzy4201** [comment]
Confirmed with Adnauseam 3.17.0, chrome 117.0.5938.92

**Comment by dhowe** [comment]
I've committed a potential fix via our filter list. Would be great if someone wanted to give a test:
1. Go to Menu->Settings->Filter-lists
2. Click `update` for 'AdNauseam filters', then revisit the site

<img width="703" alt="Screenshot 2023-09-24 at 2 24 56 AM" src="https://github.com/dhowe/AdNauseam/assets/737638/ee23ce7b-a094-47cc-a0b6-0f816e1d51f5">

**Comment by Ozzy4201** [comment]
Does not seem to have worked for me. Will update if i get another ad.

**Comment by Ozzy4201** [comment]
Yep. Midroll ad during a Veritaseum video.

**Comment by RowanSkie** [comment]
Updated mine. It went from every video to every few videos.
Brave Version 1.58.131 Chromium: 117.0.5938.92

**Comment by JCD3nt0n** [comment]
Confirming, happens less but every 13 videos or so I get the same behavior.
Double ads still popping up, skipping first still kills the second.
Also double down on with the purge button updating the entire thing and then using the same method as in bug report #2387 problem persists.

**Comment by undeadcorvid** [comment]
Still getting midroll ads, yep. And like JCD3nt0n said, you do at least kill the second ad by skipping the first. 

Purging and updating does not help. I'm on Firefox 117.0.1 (64-bit)

**Comment by U2C9727A4** [comment]
> Confirming that firefox 111.0.1 adnauseum 3.17.0 Black screen audio only, only the time skip buttons pop up for the first ad video and hitting skip button when unlocked terminates any all the remaining adds without playing the next. Changed profiles, reinstalled firefox, ditto for adnauseum and even double down on the blocklists.

I am getting the exact same issue. An ad with sound but no video. Theres also the skip ad button which makes me wait for 5 seconds. However ive been able to observe this issue in private tabs. Some of the newer youtube features is not given to my google acccount instantly but it is given to private tabs. Youtube might be trying out some ads that can bypass adblockers maybe, would require further investigation.

**Comment by UphillSky** [comment]
Can confirm this is happening on my end with the latest firefox, no video but audio still present

**Comment by UphillSky** [comment]
Curiosly, clicking the update does not appear to update my filters, now that I try

**Comment by blazingwinter** [comment]
Same issues for me on Chrome, thought it was me just being lazy and not having updated this in awhile. About every other video or so will have ads on them. Refreshing will skip the beginning of video ad, but midroll ads still happen. I'm rarely ever getting the option for skipping any of them, especially annoying with double or triple ads. Filter update didn't help on my end, I did see that the number changed, but nothing happened.

**Comment by mneunomne** [comment]
Can also confirm this issue. But now after update I'm having a hard time reproducing it again. Trying to understand what is causing it since the filters are indeed updated with uBlock and there are no adn-allowed rules going through with strict-block turned on.

**Comment by mneunomne** [comment]
Most probable cause of this is the fact that we didn't manage to keep up with uBlock Origin for some time, and the scriptlets and procedural filters are not up-to-date to the filters present in the filter uBlock filter list. Will try to merge up to 1.50 as fast as possible to address this issue. 

https://github.com/dhowe/AdNauseam/issues/2390

**Comment by RowanSkie** [comment]
Okay, it took only a few hours but now it's back to almost every video that has ads.

**Comment by adlion** [comment]
I have  a similar behavior.
On youtube the ads are black screen, the skip ad  button is shown and even after refreshing filters list or purging and re-downloading the issue is still there.

I am on ubuntu 22.0 LTS with Firefox 117.0.1-2

**Comment by U2C9727A4** [comment]
> > Confirming that firefox 111.0.1 adnauseum 3.17.0 Black screen audio only, only the time skip buttons pop up for the first ad video and hitting skip button when unlocked terminates any all the remaining adds without playing the next. Changed profiles, reinstalled firefox, ditto for adnauseum and even double down on the blocklists.
> 
> I am getting the exact same issue. An ad with sound but no video. Theres also the skip ad button which makes me wait for 5 seconds. However ive been able to observe this issue in private tabs. Some of the newer youtube features is not given to my google acccount instantly but it is given to private tabs. Youtube might be trying out some ads that can bypass adblockers maybe, would require further investigation.

CONFIRMED Ive been starting to see ads on regular youtube aswell. Youtube might be trying to implement stuff to bypass adblockers.

**Comment by mneunomne** [comment]
I just made a new pre-release which is merged to uBlock Origin's latest version 1.52.2, and it seems that the ads are not showing anymore, but requires more testing. Would be nice if you could also submit other possible issues with the application since I had to do these merges quite fast since this was an emergency with the ads showing.

https://github.com/dhowe/AdNauseam/releases/tag/v3.17.9b1

Let me know if the ads on youtube persist, and make sure the filter lists are updates.

**Comment by U2C9727A4** [comment]
> I just made a new pre-release which is merged to uBlock Origin's latest version 1.52.2, and it seems that the ads are not showing anymore, but requires more testing. Would be nice if you could also submit other possible issues with the application since I had to do these merges quite fast since this was an emergency with the ads showing.
> 
> https://github.com/dhowe/AdNauseam/releases/tag/v3.17.9b1
> 
> Let me know if the ads on youtube persist, and make sure the filter lists are updates.
> 
> (maybe its a good idea to install it on a separate browser profile, since this is a beta release)

I can give it a try. How can i install it?

**Comment by U2C9727A4** [comment]
Ive attempted to install the beta extension that supposedly fixes this issue but have been unable to. (Unsigned extensions are not allowed even after doing about:config stuff)

**Comment by mneunomne** [comment]
Which browser you are using? If Firefox you need to set the debug mode and add temporary extension manually.

**Comment by mneunomne** [comment]
Tested more now and seems that this issue is now fixed on lastest pre-release / on master branch.

**Comment by SkylerFur** [comment]
Only lite/mild testing, ~~however selecting a recommended video below the current playing video no-longer has any ad.~~ 
Spoke too soon, went to a channel to test Playlist, and I got Ads. 
![Screenshot_2023-09-27_16-10-43](https://github.com/dhowe/AdNauseam/assets/1529743/ea140379-4e2e-4a22-a8ee-127f6affd20c)

![Screenshot_2023-09-27_16-14-51](https://github.com/dhowe/AdNauseam/assets/1529743/425a4aa0-78e6-421e-a893-77f49d3171aa)

**Comment by SkylerFur** [comment]
> https://github.com/dhowe/AdNauseam/releases/tag/v3.17.9b1
> 
> Let me know if the ads on youtube persist, and make sure the filter lists are updates.

Oop turns out I'm incompetent, completely buggered the whole thing up. Yes it seems to be working now.

**Comment by U2C9727A4** [comment]
> Which browser you are using? If Firefox you need to set the debug mode and add temporary extension manually.

Got it, thank you. Ill test it now

**Comment by U2C9727A4** [comment]
> Tested more now and seems that this issue is now fixed on lastest pre-release / on master branch.

I can confirm too, I no longer see ads. Hopefully a new stable release will be on mozilla addons shortly!

**Comment by RowanSkie** [comment]
Is it safe to use git pull/clone instead of me waiting for prereleases and stable releases? Brave/Chronium user here.

**Comment by SkylerFur** [comment]
> Is it safe to use git pull/clone instead of me waiting for prereleases and stable releases? Brave/Chronium user here.

I mean like 
> https://github.com/dhowe/AdNauseam/releases/tag/v3.17.9b1
This is a pre-release you can use right now

**Comment by RowanSkie** [comment]
> > Is it safe to use git pull/clone instead of me waiting for prereleases and stable releases? Brave/Chronium user here.
> 
> I mean like
> 
> > https://github.com/dhowe/AdNauseam/releases/tag/v3.17.9b1
> 
> This is a pre-release you can use right now

Either way, the advertisements have disappeared now.

**Comment by JCD3nt0n** [comment]
Confirming OOTB that [v3.17.9b1](https://github.com/dhowe/AdNauseam/releases/tag/v3.17.9b1) after +10 videos nothing is popping up.
Further testing and adding my own lists at a later date to test on other platforms but so far on windows desktop Firefox 117.0.1 it just works™, will report in further details in a few hours.

**Comment by mneunomne** [comment]
Thank you all for helping us with this and giving us updates. I have now submited the new version 3.18.0 at the ad stores and should be available for auto-update soon.

**Comment by JCD3nt0n** [comment]
Ah so it's going it's to them to solve the debacle, alright if the only thing bypassing it is the these types of newer ones and none of the other video based ones I will survive until they are done with the filters.

**Comment by SkylerFur** [comment]
So I'm pretty sure I've found a new YouTube Ad "bug" as I'm watching a video suddenly the audio cuts out, but seeking doesn't fix it. It's happening right about when a Mid-Roll ad should happen, I suspect that the video isn't being paused and the Ad isn't loading; however the audio is cut. The inverse of the Black video W/ Audio only Ads.

**Comment by dhowe** [comment]
fixed in v3.18.0, thanks to @mneunomne 
closing for now
