### ISSUE TITLE
fb profile pictures collected as Ads

### ISSUE THREAD

**Issue by leoneckert** [dhowe/AdNauseam#426]
it still has to be resolved how the profile pictures are detected as ads. When following the link they are collected with (in the vault), they lead to the people's profiles on fb. similar links from actual ads collected on Facebook lead, as expected, to advertising pages (e.g. Verizon). 
one guess is that they come from profiles that are associated with "Sponsored Posts" on fb, they often come with "your friends [names of friends] like [advertiser]" or sometimes Sponsired content appears if friends or friends of friends happened to comment. Maybe, when collecting that, profile photos are collected too.

Some captures:
<img width="549" alt="screen shot 2016-09-21 at 00 06 34" src="https://cloud.githubusercontent.com/assets/14130931/18697779/953c796a-7f92-11e6-93fc-00971d1c7bbd.png">
(^Leads to Verizon)
<img width="555" alt="screen shot 2016-09-21 at 00 06 21" src="https://cloud.githubusercontent.com/assets/14130931/18697782/9de2a1c0-7f92-11e6-806d-9ea81940a5a3.png">
(^Leads to profile)
<img width="519" alt="screen shot 2016-09-21 at 00 18 43" src="https://cloud.githubusercontent.com/assets/14130931/18697784/a704391c-7f92-11e6-99a9-ea21676f0049.png">
(^Sponsored Post with "Friends liking it")

**Comment by leoneckert** [comment]
I am very sure profiles presented as "People you might know" are detected as Ads.

**Comment by cqx931** [comment]
Where do you see this"People you might know" section when you find profiles pics are collected? I checked the one under friends/requests, but there is no profile pics collected there.
<img width="644" alt="screen shot 2016-09-22 at 10 31 03 am" src="https://cloud.githubusercontent.com/assets/3056154/18735348/b93b20be-80af-11e6-89af-c3f0518e4cd7.png">

**Comment by leoneckert** [comment]
this is the section I mean. I hardly ever see or notice it, but I do recognise all the photos in that section from my AdNauseam vault.
<img width="525" alt="screen shot 2016-09-22 at 10 36 43" src="https://cloud.githubusercontent.com/assets/14130931/18752943/f0945af6-80b1-11e6-9a9c-aa5d85ef381b.png">

**Comment by cqx931** [comment]
hmm. Is it in your timeline page? Interesting...I don't have this section on my page.

**Comment by leoneckert** [comment]
yes,  took that screenshot using a profile without adn. right now I discovered that when using adn, the panel is actually hidden which explains why the images are collected as ads I guess:

<img width="541" alt="screen shot 2016-09-24 at 19 57 00" src="https://cloud.githubusercontent.com/assets/14130931/18811957/18df5d86-8291-11e6-9fcb-2ae46084ef33.png">

**Comment by dhowe** [comment]
Generally we do not allow ads with internal targetUrls. So an ad found on xyz.com which links to a URL on xyz.com (or www.xyz.com) is ignored. However, some sites use this mechanism (generally with a redirect) for serving real ads. The classic example is Google where all text-ads go first to a Google URL, and are then redirected. To accommodate these exceptions, core.js has an array of domains  called `internalLinkDomains`. Facebook, which also serves its ads this way (or at least, they used to) is on this list, thus the target URLs that you see above. 

So, 2 options: 1) remove Facebook from  `internalLinkDomains`, or 2) add an exception rule in adnauseam.txt for only the types of images discussed above.

My guess is that option #1 will likely break all Ad collection for Facebook, so we are probably left only with #2

**Comment by leoneckert** [comment]
wait so by exception rule you mean what exactly? Don't all the rules/regex in adnauseam.txt attempt to find ads? But we are in a situation where something is thought to be an ad that is actually not?
I just took the 'facebook.com' out of internalLinkDomains, but they are still all collected - does this make sense? Shouldn't they then NOT be collected as the link to the page itself?

**Comment by dhowe** [comment]
See excpetion rules: https://adblockplus.org/filter-cheatsheet

**Comment by dhowe** [comment]
leon: I just took the 'facebook.com' out of internalLinkDomains, but they are still all collected - does this make sense? Shouldn't they then NOT be collected as the link to the page itself?

**Comment by dhowe** [comment]
Check the ad's targetUrl -- if it goes to facebook.com/*, when it is not in the internalLinkDomains list, then there is a bug somewhere

**Comment by leoneckert** [comment]
That seems like a bug then.
This is in the bin/build that I am running (no facebook.com listed):
<img width="1022" alt="screen shot 2016-09-27 at 00 53 13" src="https://cloud.githubusercontent.com/assets/14130931/18860604/ea5b9b4c-844c-11e6-9faf-97cd3311417d.png">
and in the console when on facebook:
<img width="459" alt="screen shot 2016-09-27 at 00 54 08" src="https://cloud.githubusercontent.com/assets/14130931/18860609/fb52fbf2-844c-11e6-97f2-7b2d56a3c796.png">

**Comment by leoneckert** [comment]
mhm do I get this wrong. I tried these exception filters (with facebook,com back in internalLinkDomains):
@@facebook.com##img[src^="https://scontent-lga3-1.xx"]  @@facebook.com##img[style*="width:320px;height:320px"] 
@@facebook.com##img[style*="width:136px;height:136px"] 
@@img[class*="_s0"]
@@._s0
@@div[class*="_6a"]  

this is the element detected:

<img width="1280" alt="screen shot 2016-09-27 at 01 36 39" src="https://cloud.githubusercontent.com/assets/14130931/18861440/302c2f32-8453-11e6-9a78-85015ef3c4e7.png">

**Comment by dhowe** [comment]
This is what I see when I remove facebook.com from internalLinkDomains:

![screen shot 2016-09-27 at 4 17 53 pm](https://cloud.githubusercontent.com/assets/737638/18865484/16ad3490-84ce-11e6-9787-efbfe3180593.png)

**Comment by leoneckert** [comment]
Oh I see! Your screenshot is from background.js right? That makes sense. I assumed when they are detected in the page's console, then they are collected. But I guess core.js receives data from parser.js and then applies it's own rejection rules? 
Will try to work with those exceptions again to solve this now.

**Comment by leoneckert** [comment]
for my understanding. when I take facebook.com out of internalLinkDomains, none of the ads (and what it mistakingly assumes to be ads) will be collected, yet they will still be hidden because that is happening earlier than core.js?

**Comment by leoneckert** [comment]
have you used the @@ exception rules in adn before? I tried combinations of very general stuff as well without any luck. 
I think I technically understand more or less what's going on between parser.js and core.js, but no matter what I do, once the "People you may know" box is it, parser.js detects 20+ 'ads'. Any more ideas what to try out? @cqx931 ? thanks!

**Comment by dhowe** [comment]
> for my understanding. when I take facebook.com out of internalLinkDomains, none of the ads (and what it mistakingly assumes to be ads) will be collected, yet they will still be hidden because that is happening earlier than core.js?

Hiding happens exclusively based on rules, thus we need a cosmetic-exception rule so that hiding doesn't occur for the these non-ads? Have we checked what ABP and/or uBlock are doing for fb? I would guess that they are not hiding actual content...

**Comment by leoneckert** [comment]
I just found that uBlock is also hiding this box/identifying it falsely as an ad

**Comment by dhowe** [comment]
Ok, so then it is not our problem (though we still might want to NOT collect them). 

Generally-speaking, we always want to verify that an ad is blocked/hidden by uBlock before working on it.

It would be good to check ABP as well, as they have been at the forefront of this recent conflict with fb.

**Comment by leoneckert** [comment]
In ADB I can see the box. Sally recommended to test if maybe a JS is blocking it and by allowing some scripts from the logger I can get the content back on fb. 
I would read this https://github.com/dhowe/AdNauseam/issues/279 and then try that. Or should I go with " it is not our problem" ?

**Comment by cqx931** [comment]
@dhowe my main problem of taking over this ticket is that I can't see the people you may know section in my page... I will try with other accounts and report back.

**Comment by cqx931** [comment]
here is what I find.
The problem is caused by these following rules from Easy List when I use the logger to check the rules:
![screen shot 2016-09-28 at 2 06 59 pm](https://cloud.githubusercontent.com/assets/3056154/18902533/28072076-8586-11e6-9784-73873ad5b4c2.png)

Then I opened the latest easy list txt file and can't find the exact rules there. 
So I think this should be an issue that they had before but solved now.(by having more specific selectors)
After I update the easylist in AdNauseam, I don't see this issue anymore.

**Comment by dhowe** [comment]
Interesting... The place to check for the most up-to-date rules is in the dhowe/uAssets [repo](https://github.com/dhowe/uAssets), which is where rules are loaded from during the build process (you should make sure to fetch/merge this repo every so often) . 

But the errors in #453 were caused by update attempts for the included uBlock lists, rather than the 3rd-party lists, but it is something to keep an eye on... I have to work out a better way to keep that repo  current and the checksums (which are used to validate updates) up-to-date

**Comment by cqx931** [comment]
can this be closed now?

**Comment by leoneckert** [comment]
- [x] The profile pictures are not collected anymore
they are still hidden though,
and the other ads are also (hidden, but) not collected. I guess that just gets part of https://github.com/dhowe/AdNauseam/issues/356

**Comment by dhowe** [comment]
Ads need to be hidden _and_ collected. Best case beyond that is that non-ads are not hidden (with an adnauseam-specific exception rule. If this is not possible (or not easy) then we can leave these non-ads hidden but not collected (as this is a filter problem, not a code problem).

**Comment by leoneckert** [comment]
my bad. I thought that was solved with @cqx931 's Easy List discoveries above, but the only reason things (both non Ads and Ads) were not collected for me anymore was that facebook.com is not in internalLinkDomains in the current master, is that intentional?

**Comment by dhowe** [comment]
I thought we had decided to remove it from the internalLinkDomains list -- if this is not correct, then please re-add...

**Comment by cqx931** [comment]
just added back facebook to internalLinkDomains list.
Checked that normal ads could be collected but not people you may know.
https://github.com/dhowe/AdNauseam/pull/490/commits/e5922236e024a358609ba1d1df283cf9725fdbf0

**Comment by leoneckert** [comment]
they are still collected but hidden differently. Now, for me, the WHOLE box of "People You may know" (all in screenshot below) is hidden. Before, the title of it remained while only the images and names were hidden. Maybe it's worth another try to write some filters. - I will try later today. 

<img width="529" alt="screen shot 2016-10-05 at 18 08 15" src="https://cloud.githubusercontent.com/assets/14130931/19133555/e4fbc16e-8b26-11e6-9a73-c956ebe45615.png">

**Comment by cqx931** [comment]
interesting... so you get the latest easylist and clear all browser data, but still get the profile photos? I don't see that happening to me any more...Can you see check selector is working from the logger?

**Comment by leoneckert** [comment]
Found the reason! It seems like the "People You May Know" box has been consciously decided to be considered an Ad in uBlock - which I guess can be argued to be true, but is certainly debatable, it definitely looks odd to me to see faces of people I might know in the vault.  
Here it is in assets/ublock/filters.txt (this is in the bin/build, not sure where exactly this is pulled from during the build):
![screen shot 2016-10-09 at 16 26 08](https://cloud.githubusercontent.com/assets/14130931/19223440/02651f74-8e3e-11e6-9f48-baf3bfc98372.png)

If I delete those lines, the box is not hidden and profile photos not collected. The question is I guess if AdNauseam considers this an Ad too.

**Comment by dhowe** [comment]
That file (assets/ublock/filters.txt) is packaged from uAssets and then updated in the extension via the auto or manual update options in settings. When I merge in new changes from the upstream uAssets, it gets updated for our builds.

**Comment by leoneckert** [comment]
so are we just going with uBlock's standard considering this an ad?

**Comment by dhowe** [comment]
Unless anyone has a contrary opinion?

**Comment by leoneckert** [comment]
I do think going with uBlocks standards makes a lot of sense and it feels not so appropriate to write an exception to contradict in such a particular detail. 
Those suggestions are targeted (assumedly based your fb behaviour (friends, likes, clicks)), but are no ads that directly contribute to their profit (of course they do benefit from the network growing in the longer run). 
During development, when deleting/reloading ADN regularly, the vault can look strange when it's full of clearly non-"addy" images, but I think when collecting a lot more ads that wouldn't be so obvious. 

I am aware there is probably a lot such edge cases, just throwing those thoughts out. 

<img width="1175" alt="screen shot 2016-10-11 at 18 29 28" src="https://cloud.githubusercontent.com/assets/14130931/19291098/1a1ab85a-8fe1-11e6-9c84-acedabe3e17b.png">

**Comment by dhowe** [comment]
Sounds right to me -- if anyone else has a strong opinion, pls reopen and add it below...
