### ISSUE TITLE
Visible ads blocked by AdBlock Plus

### ISSUE THREAD

**Issue by pallaire** [dhowe/AdNauseam#748]
From amazon, on this website : http://www.gocurrycracker.com/
AdNauseam: 3.0.4
Firefox: 50.1.0

![go_curry_cracker__-_retire_early__travel_the_world_](https://cloud.githubusercontent.com/assets/400709/21857528/a2fb6be2-d7da-11e6-8a23-b0160c94534c.jpg)

**Comment by pallaire** [comment]
On the same site, in posts, there are some other ones that are left over. 

http://www.gocurrycracker.com/something-for-everybody/

![something_for_everybody_-_go_curry_cracker_](https://cloud.githubusercontent.com/assets/400709/21857624/f13f6e7a-d7da-11e6-8464-fd0712a87602.jpg)

**Comment by pallaire** [comment]
Two more on another financial site : http://www.mrfreeat33.com/its-not-about-the-money-rent-versus-buy/

![it s_not_about_the_money__rent_versus_buy_ _mr__free_at_33](https://cloud.githubusercontent.com/assets/400709/21857839/ba3ab19a-d7db-11e6-8e06-9b39668d5014.jpg)

**Comment by dhowe** [comment]
thats great, thanks @pallaire

**Comment by dhowe** [comment]
@pallaire, please update your filter lists as follows:

1. Click on the AdNauseam menu, then select Settings, then select the '3rd-party filters' tab
2. Click 'Purge All Caches', then click 'Apply Changes', then click 'Update Now'
3. Then verify that you have at least 155 rules for 'adnauseam.txt', repeat if not

Then re-test those pages and let me know if you still see ads (I've added some new rules which should fix the issue)

thanks

**Comment by pallaire** [comment]
Some are gone, but I still get the brcclx.com on : http://www.gocurrycracker.com/something-for-everybody/   ( the second one I added on top )

**Comment by dhowe** [comment]
Ok, we'll have to check that one again tomorrow... thanks for the reports

https://cloud.githubusercontent.com/assets/400709/21857624/f13f6e7a-d7da-11e6-8464-fd0712a87602.jpg

**Comment by dhowe** [comment]
@cqx931 can you check the above page for ads (http://www.gocurrycracker.com/) after updating your adnauseam list (should have >= 156 entries) -- I can't recreate the issue at moment...

https://cloud.githubusercontent.com/assets/400709/21857624/f13f6e7a-d7da-11e6-8464-fd0712a87602.jpg

**Comment by cqx931** [comment]
When I check http://www.gocurrycracker.com/something-for-everybody/, the ad is hidden with the corresponding parser in adnauseam.txt.

**Comment by dhowe** [comment]
@pallaire I'm going to close this -- but pls let us know if you find other cases
